export const SUBMIT_REQUESTING = 'SUBMIT_REQUESTING';
export const SUBMIT_SUCCESS = 'SUBMIT_SUCCESS';
export const SUBMIT_ERROR ='SUBMIT_ERROR'
export const FETCH_REQUESTING = 'FETCH_REQUESTING';
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR"


